import type { CourseSource, CourseSourceRecord } from '@/lib/course-sources/types'

/**
 * A small, deterministic baseline. These records keep the repository useful
 * when every upstream API is unavailable and are intentionally limited to
 * canonical pages that a human can review.
 */
export const CURATED_COURSES: CourseSourceRecord[] = [
  {
    provider: 'freecodecamp',
    externalId: 'responsive-web-design-2022',
    title: 'Responsive Web Design',
    description: 'HTML, CSS, accessibility, responsive layouts, and practical page projects.',
    canonicalUrl: 'https://www.freecodecamp.org/learn/2022/responsive-web-design/',
    skillTags: ['html', 'css', 'responsive design', 'web accessibility', 'frontend development'],
    level: 'beginner',
    durationMinutes: 300,
    language: 'en',
    regions: [],
    accessType: 'free',
    qualityScore: 0.92,
    trusted: true,
    discoveredVia: 'curated',
  },
  {
    provider: 'freecodecamp',
    externalId: 'javascript-algorithms-v8',
    title: 'JavaScript Algorithms and Data Structures',
    description: 'Core JavaScript, data structures, algorithms, and project-based exercises.',
    canonicalUrl: 'https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/',
    skillTags: ['javascript', 'algorithms', 'data structures', 'frontend development'],
    level: 'beginner',
    durationMinutes: 600,
    language: 'en',
    regions: [],
    accessType: 'free',
    qualityScore: 0.92,
    trusted: true,
    discoveredVia: 'curated',
  },
  {
    provider: 'freecodecamp',
    externalId: 'relational-database',
    title: 'Relational Database',
    description: 'SQL, PostgreSQL, Bash, Git, and relational database projects.',
    canonicalUrl: 'https://www.freecodecamp.org/learn/relational-database/',
    skillTags: ['sql', 'postgresql', 'relational databases', 'bash', 'git'],
    level: 'beginner',
    durationMinutes: 600,
    language: 'en',
    regions: [],
    accessType: 'free',
    qualityScore: 0.94,
    trusted: true,
    discoveredVia: 'curated',
  },
  {
    provider: 'freecodecamp',
    externalId: 'data-analysis-with-python',
    title: 'Data Analysis with Python',
    description: 'NumPy, pandas, Matplotlib, and practical data-analysis projects.',
    canonicalUrl: 'https://www.freecodecamp.org/learn/data-analysis-with-python/',
    skillTags: ['python', 'data analysis', 'pandas', 'numpy', 'matplotlib'],
    level: 'intermediate',
    durationMinutes: 300,
    language: 'en',
    regions: [],
    accessType: 'free',
    qualityScore: 0.93,
    trusted: true,
    discoveredVia: 'curated',
  },
  {
    provider: 'youtube',
    externalId: 'rfscVS0vtbw',
    title: 'Learn Python - Full Course for Beginners',
    description: 'A complete introductory Python course from freeCodeCamp.org.',
    canonicalUrl: 'https://www.youtube.com/watch?v=rfscVS0vtbw',
    skillTags: ['python', 'programming fundamentals'],
    level: 'beginner',
    durationMinutes: 266,
    language: 'en',
    regions: [],
    accessType: 'free',
    qualityScore: 0.88,
    trusted: true,
    discoveredVia: 'curated',
  },
  {
    provider: 'google',
    externalId: 'machine-learning-crash-course',
    title: 'Machine Learning Crash Course',
    description: 'Google’s practical introduction to machine-learning concepts and production practice.',
    canonicalUrl: 'https://developers.google.com/machine-learning/crash-course',
    skillTags: ['machine learning', 'tensorflow', 'classification', 'regression'],
    level: 'intermediate',
    durationMinutes: 900,
    language: 'en',
    regions: [],
    accessType: 'free',
    qualityScore: 0.9,
    trusted: true,
    discoveredVia: 'curated',
  },
  {
    provider: 'google',
    externalId: 'technical-writing-one',
    title: 'Technical Writing One',
    description: 'Google’s course on clear technical documentation for engineers and technical teams.',
    canonicalUrl: 'https://developers.google.com/tech-writing/one',
    skillTags: ['technical writing', 'documentation', 'written communication'],
    level: 'beginner',
    durationMinutes: 120,
    language: 'en',
    regions: [],
    accessType: 'free',
    qualityScore: 0.86,
    trusted: true,
    discoveredVia: 'curated',
  },
  {
    provider: 'khan-academy',
    externalId: 'intro-to-sql',
    title: 'Intro to SQL: Querying and Managing Data',
    description: 'Interactive SQL lessons covering queries, aggregation, joins, and data modification.',
    canonicalUrl: 'https://www.khanacademy.org/computing/computer-programming/sql',
    skillTags: ['sql', 'databases', 'data analysis'],
    level: 'beginner',
    durationMinutes: 240,
    language: 'en',
    regions: [],
    accessType: 'free',
    qualityScore: 0.88,
    trusted: true,
    discoveredVia: 'curated',
  },
  {
    provider: 'khan-academy',
    externalId: 'statistics-probability',
    title: 'Statistics and Probability',
    description: 'Probability, distributions, inference, regression, and statistical reasoning.',
    canonicalUrl: 'https://www.khanacademy.org/math/statistics-probability',
    skillTags: ['statistics', 'probability', 'data analysis', 'regression'],
    level: 'beginner',
    durationMinutes: 600,
    language: 'en',
    regions: [],
    accessType: 'free',
    qualityScore: 0.87,
    trusted: true,
    discoveredVia: 'curated',
  },
  {
    provider: 'mit-ocw',
    externalId: '6-0001-fall-2016',
    title: 'Introduction to Computer Science and Programming in Python',
    description: 'MIT OpenCourseWare materials for computational thinking and Python programming.',
    canonicalUrl: 'https://ocw.mit.edu/courses/6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016/',
    skillTags: ['python', 'computer science', 'algorithms', 'problem solving'],
    level: 'beginner',
    durationMinutes: 600,
    language: 'en',
    regions: [],
    accessType: 'free',
    qualityScore: 0.82,
    trusted: true,
    discoveredVia: 'curated',
  },
  {
    provider: 'w3schools',
    externalId: 'typescript-tutorial',
    title: 'TypeScript Tutorial',
    description: 'Concise lessons and examples covering TypeScript syntax and types.',
    canonicalUrl: 'https://www.w3schools.com/typescript/',
    skillTags: ['typescript', 'javascript', 'frontend development'],
    level: 'beginner',
    durationMinutes: 180,
    language: 'en',
    regions: [],
    accessType: 'free',
    qualityScore: 0.72,
    trusted: true,
    discoveredVia: 'curated',
  },
  {
    provider: 'w3schools',
    externalId: 'git-tutorial',
    title: 'Git Tutorial',
    description: 'A practical introduction to Git, GitHub, branching, and collaboration.',
    canonicalUrl: 'https://www.w3schools.com/git/',
    skillTags: ['git', 'github', 'version control'],
    level: 'beginner',
    durationMinutes: 120,
    language: 'en',
    regions: [],
    accessType: 'free',
    qualityScore: 0.72,
    trusted: true,
    discoveredVia: 'curated',
  },
]

export const curatedCourseSource: CourseSource = {
  id: 'curated',
  enabled: () => process.env.COURSE_SOURCES_ENABLED !== '0',
  async collect() {
    return CURATED_COURSES
  },
}
